Retail_Banking_Group2/Controllers/CashierController.cs
using Retail_Banking_Group2.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Retail_Banking_Group2.Controllers
{
    public class CashierController : Controller
    {
        bankEntities bank = new bankEntities();

        public ActionResult cashierView()
        {

            try
            {
                ViewBag.username = Session["userName"];
                if (Session["userName"] != null && Session["userroleId"].ToString() == "2")
                {
                    List<sp_viewCashier_group2_Result> li = new List<sp_viewCashier_group2_Result>();
                    li = bank.sp_viewCashier_group2().ToList();
                    return View(li);
                }
                else
                {
                    return Redirect("../login/login");
                }
            }
            catch (Exception e)
            {

                throw e;
            }

        }

        public ActionResult deposit(long? id, decimal? balamt)
        {
            try
            {
                ViewBag.username = Session["userName"];
                if (Session["userName"] != null && Session["userroleId"].ToString() == "2")
                {
                    cashierViewAccountbyId_group2_Result objAccount = new cashierViewAccountbyId_group2_Result();
                    if (id != null)
                    {

                        objAccount = bank.cashierViewAccountbyId_group2(id).FirstOrDefault();
                        return View(objAccount);
                    }


                    return View();
                }
                else
                {
                    return Redirect("../login/login");
                }
            }
            catch (Exception e)
            {

                throw e;
            }

        }

        [HttpPost]
        public ActionResult deposit(addaccount_group2 objTran,long id, decimal balamt)
        {
            try
            {
                ViewBag.username = Session["userName"];
                cashierViewAccountbyId_group2_Result objAccount = new cashierViewAccountbyId_group2_Result();
                if (objTran.DepositAmount <= 0 || objTran.DepositAmount > 100000 || objTran.DepositAmount == null)
                {
                    objAccount.AccountId = objTran.AccountId;
                    objAccount.DepositAmount = objTran.DepositAmount;
                    ViewBag.message = "enter valid amount";
                    return View(objAccount);
                }
                else
                {
                    ObjectParameter objParam = new ObjectParameter("latestbalance", typeof(decimal));
                    int result;
                    if (objTran.AccountType == 1)
                    {
                        result = bank.sp_Deposit_group2(id, "Savings ", "deposit", objTran.DepositAmount, balamt, objParam);
                    }
                    else
                    {
                        result = bank.sp_Deposit_group2(id, "Current ", "deposit", objTran.DepositAmount, balamt, objParam);
                    }
                    if (result > 0)
                    {
                        this.bank.SaveChanges();
                        TempData["Messdep"] = "Successfully Deposited! The new available balance is Rs." + objParam.Value;

                    }
                    return RedirectToAction("cashierView");

                }



            }

            catch (Exception e)
            {

                throw e;
            }

        }

        public ActionResult withdraw(long? id, decimal? balamt)
        {
            try
            {
                ViewBag.username = Session["userName"];
                if (Session["userName"] != null && Session["userroleId"].ToString() == "2")
                {
                    cashierViewAccountbyId_group2_Result objaccount = new cashierViewAccountbyId_group2_Result();
                    if (balamt == 0)
                    {
                        TempData["Messagewithdraw"] = "Your balance is RS." + balamt;
                        return RedirectToAction("cashierView");

                    }
                    else
                    {
                        if (id != null)
                        {

                            objaccount = bank.cashierViewAccountbyId_group2(id).FirstOrDefault();
                            int? transctns = bank.sp_Totaltransactions(objaccount.CustomerID, DateTime.Today.Date).FirstOrDefault();
                            int a = transctns.GetValueOrDefault();
                            if (a > 3)
                            {
                                TempData["msg"] = "transactions limit has been reached";
                                return RedirectToAction("cashierView");
                            }
                            return View(objaccount);
                        }
                    }
                    return RedirectToAction("cashierView");

                }
                else
                {
                    return Redirect("../login/login");
                }
            }
            catch (Exception e)
            {

                throw e;
            }

        }

        [HttpPost]
        public ActionResult Withdraw(addaccount_group2 withd,long id, decimal? balamt)
        {
            try
            {
                cashierViewAccountbyId_group2_Result objAccount = new cashierViewAccountbyId_group2_Result();
                if (withd.DepositAmount < 0 || withd.DepositAmount > balamt || withd.DepositAmount == 0 || withd.DepositAmount == null)
                {
                    objAccount.AccountId = withd.AccountId;
                    objAccount.DepositAmount = withd.DepositAmount;
                    ViewBag.messageinsuf = "invalid amount";

                    return View();
                }

                else
                {
//                    @AccountId bigint,
//@AccountType varchar(50),
//@TransactionType varchar(50),
//@amount money,
//@beforebalance money,
//@latestbalance money out
                    ObjectParameter objParam = new ObjectParameter("latestbalance", typeof(decimal));
                    int result;
                    if (withd.AccountType == 1)
                    {
                        result = bank.sp_WithdrawAmount_group2(id, "Savings", "withdraw", withd.DepositAmount, balamt, objParam);
                    }
                    else
                    {
                        result = bank.sp_WithdrawAmount_group2(id, "Current", "withdraw", withd.DepositAmount, balamt, objParam);
                    }
                    if (result > 0)
                    {
                        this.bank.SaveChanges();
                        TempData["Messwith"] = "Successfully Withdrawn! The new available balance is Rs." + objParam.Value;
                    }
                    return RedirectToAction("cashierView");
                }
            }
            catch (Exception e)
            {

                throw e;
            }

        }




        public ActionResult Transfer(long? id, long? cid, int? acctype, decimal? bal)
        {
            try
            {
                ViewBag.username = Session["userName"];
                if (Session["userName"] != null && Session["userroleId"].ToString() == "2")
                {
                    sp_selectCustomerAccountIdforTransfer_group2_Result cusacc = new sp_selectCustomerAccountIdforTransfer_group2_Result();
                    int NoOfacc = Convert.ToInt32(bank.sp_checknoofAccounts_group2(cid).FirstOrDefault());
                    if (NoOfacc == 2)
                    {
                        if (id != null)
                        {

                            cusacc = bank.sp_selectCustomerAccountIdforTransfer_group2(cid, id).FirstOrDefault();
                            int? transctns = bank.sp_Totaltransactions(cusacc.CustomerID, DateTime.Today.Date).FirstOrDefault();
                            int a = transctns.GetValueOrDefault();
//ALTER proc [dbo].[sp_Totaltransactions]
//@CustomerId bigint,
//@date date
//as
//begin
//select count(*) as TransactionsCount from addaccount_group2
//inner join transactiontable_group2 on addaccount_group2.AccountId=transactiontable_group2.AccountId
//where (addaccount_group2.CustomerID=@CustomerId and transactiontable_group2.dateoftransaction=@date)
//end
                            if (a > 3)
                            {
                                TempData["msg"] = "transactions limit has been reached";

                                return RedirectToAction("cashierView");
                            }
                            Session["SAccidsource"] = cusacc.AccountType;
                            Session["SAccId"] = id;
                            Session["SAccBal"] = bal;
                            Session["SAccType"] = acctype;
                          
                            if (cusacc.AccountType == 1)
                            {
                                Session["DAccType"] = "Savings";

                            }
                            else
                                Session["DAccType"] = "Current";
                        }
                        return View(cusacc);
                    }
                    else
                    {
                        TempData["notransfer"] = "This customer has only one account";
                        return RedirectToAction("cashierView");
                    }

                }


                else
                {
                    return Redirect("../login/login");
                }
            }
            catch (Exception e)
            {

                throw e;
            }

        }

        [HttpPost]

Retail_Banking_Group2/Controllers/aboutbankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Retail_Banking_Group2.Controllers
{
    public class aboutbankController : Controller
    {
        // GET: aboutbank
        public ActionResult aboutbank()
        {
            return View();
        }
    }
}

Retail_Banking_Group2/Controllers/cashieroperationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Retail_Banking_Group2.Controllers
{
    public class cashieroperationController : Controller
    {
        // GET: cashieroperation
        public ActionResult cashieroperation()
        {
            return View();
        }
    }
}

Retail_Banking_Group2/Controllers/contactbankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Retail_Banking_Group2.Controllers
{
    public class contactbankController : Controller
    {
        // GET: contactbank
        public ActionResult contactbank()
        {
            return View();
        }
    }
}

Retail_Banking_Group2/Controllers/faqbankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Retail_Banking_Group2.Controllers
{
    public class faqbankController : Controller
    {
        // GET: faqbank
        public ActionResult faqbank()
        {
            return View();
        }
    }
}

Retail_Banking_Group2/Controllers/frontpageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Retail_Banking_Group2.Controllers
{
    public class frontpageController : Controller
    {
        // GET: home
        public ActionResult frontpage()
        {
            return View();
        }
    }
}

Retail_Banking_Group2/Views/Shared/aboutbank.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Retail Banking</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>

@RenderBody()
<body style="background-color:white;background-image:url(http://www.healingandtransformation.com/wp-content/uploads/2014/05/bigstock-Sky-and-clouds-background-26443844.jpg);background-size:cover;background-repeat:no-repeat">
<nav class="navbar navbar-default " style="margin-top:-50px;margin-left:0px;background-color:black;">
    @*<div class="container">*@
    <div class="navbar-header" style="background-color:black">

        <img src=" ~/Content/logo-edited.jpg" alt="online banking " ;width="80" ; height="80" ; style="margin-top:5px;margin-left:5px">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right" style="margin-left:850px;color:white">

                <li style="color:black;font-size:20px">
                    @Html.ActionLink("Home", "frontpage", "frontpage")
                </li>
                <li style="text-emphasis-color:black;font-size:20px">@Html.ActionLink("Faq", "faqbank", "faqbank")</li>
                <li style="text-emphasis-color:black;font-size:20px">@Html.ActionLink("Contact", "contactbank", "contactbank") </li>
                <li style="text-emphasis-color:black;font-size:20px">
                    @Html.ActionLink("Login", "login", "login")
                </li>
                @*<li style="background-color:White;font-size:20px"><a href="~/Views/Shared/loginlayout.cshtml">Login</a></li>*@
            </ul>
        </div>
        <div style="margin-top:-130px;margin-left:150px">

            <h1 style="color:white">STANDARD BANK</h1>

        </div>

    </div>

</nav>



<div id="about" class="container-fluid">
    <div class="row">
        <div class="col-sm-8">
            <h2 style="color:antiquewhite;margin-top:90px">
                About Standard Bank
            </h2>
            <h4 style="margin-left:20px;align-items:center;margin-top:100px;color:white">

                bank is a financial institution that accepts deposits from the public and creates credit.Lending activities can be performed either directly or indirectly through capital markets. Due to their 
                importance in the financial stability of a country, banks are highly regulated in most countries. Most nations have institutionalized a system known as fractional reserve banking under which banks. 
                In addition to other regulations intended to ensure liquidity, banks are generally subject to minimum capital requirements based on an international set of capital standards, known as the Basel Accords.

                 the Berenbergs and the Rothschilds  – have played a central role over many centuries. The oldest existing retail bank is Banca Monte dei Paschi di Siena, while the oldest existing merchant bank is Berenberg Bank.
            </h4>
        </div>
        <div class="col-sm-4">
         
        </div>
    </div>
</div>

<div class="container-fluid bg-grey">

        <div class="col-sm-4">
      
        </div>
        <div class="col-sm-8">
          
    
    </div>
</div>
</html>

Retail_Banking_Group2/Views/Shared/cashierViewlayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <font style="margin-left:10px;margin-left:400px;font-size:50px;color:white"> STANDARD BANK</font>
    <body style="background-color:white;background-image:url(http://www.healingandtransformation.com/wp-content/uploads/2014/05/bigstock-Sky-and-clouds-background-26443844.jpg);background-size:cover;background-repeat:no-repeat">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Cashier View</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">

            <ul class="nav navbar-nav">
                <li style="background-color:white;font-size:20px">
                    @Html.ActionLink("HOME", "cashieroperation", "cashieroperation")
                </li>
                <li style="background-color:white;font-size:20px">
                    @Html.ActionLink("WITHDRAW", "withdraw", "Cashier")
                </li>
                <li style="background-color:white;font-size:20px">
                    @Html.ActionLink("DEPOSIT", "deposit", "Cashier")
                </li>
                <li style="background-color:white;font-size:20px">
                    @Html.ActionLink("TRANSFER", "#", "#")
                </li>
                <li style="background-color:white;font-size:20px">
                    @Html.ActionLink("VIEW", "casierView", "Cashier")
                </li>

            </ul>
        </div>
    </nav>
    @RenderBody()
    <h2> copy right</h2>
    @*<div class="container">
        <h3>Basic Navbar Example</h3>
        <p>A navigation bar is a navigation header that is placed at the top of the page.</p>
    </div>*@

</body>
</html>

Retail_Banking_Group2/Views/Shared/cashieroperation.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
   
    <body style="background-color:white;background-image:url(http://www.healingandtransformation.com/wp-content/uploads/2014/05/bigstock-Sky-and-clouds-background-26443844.jpg);background-size:cover;background-repeat:no-repeat">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Cashier</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://cdnjs_cloudflare.com/ajax/libs/popper_js/1.12.6/umd/popper.min.js"></script>
        <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
        <script srx="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>

</head>

<body>

    <nav class="navbar navbar-default" style="background-color:black">
        <font style="margin-left:10px;margin-left:10px;font-size:50px;color:white"> STANDARD BANK</font>
        <div class="container-fluid">
           
            <ul class="nav navbar-nav" style="margin-left:850px">
                <li style="color:white;font-size:20px">
                    @Html.ActionLink("Home", "cashieroperation", "cashieroperation")
                </li>
         
                <li style="color:white;font-size:20px">
                    @Html.ActionLink("Ministatement", "PrintStatement", "Cashier")
                </li>
                <li style="color:white;font-size:20px">
                    @Html.ActionLink("View", "cashierView", "Cashier")
                </li>
                <li style="color:white;font-size:20px">
                    @Html.ActionLink("Logout", "logout", "login")
                </li>

            </ul>
        </div>
    </nav>
    @RenderBody()
    <<div style="margin-top:50px;margin-left:500px">
    <img src="~/Content/nre-fixed-deposit.jpg" alt="online banking" width="400" height="400">
</div>
    <footer style="margin-left:0px;margin-top:0px;background-color:black;margin-bottom:0px;">

        <div style="margin-left:50px;font-size:larger">
            <a href="#"><span class="label label-info">Branch Details</span></a>
            <a href="#"><span class="label label-info">IFSC Codes</span></a>
            <a href="#"><span class="label label-info">Credit cards</span></a>
            <a href="#"><span class="label label-info">Interest rates</span></a>
            @*| <i class="icon-user"></i> <a href="#">Admin</a>*@
            <div style="margin-top:10px">
                <i class="icon-share"></i> <a href="#"> <h4 style="margin-left:700px;color:white;margin-top:-25px">Contact us 24*7 on 08008-88558855</h4></a>
                <h3 style="color:white">copyright *standartbanking.com Group_2</h3>
            </div>
            </h2>
    </footer>
</body>
</html>

Retail_Banking_Group2/Views/Shared/contactbank.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Retail Banking</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    @*<font style="margin-left:10px;margin-top:1px;font-size:50px;color:white;position:fixed"> STANDARD BANK</font>*@

  
</head>

<body style="background-color:white;background-image:url(http://www.healingandtransformation.com/wp-content/uploads/2014/05/bigstock-Sky-and-clouds-background-26443844.jpg);background-size:cover;background-repeat:no-repeat">

    <nav class="navbar navbar-default " style="margin-top:-50px;margin-left:0px;background-color:black;">
        @*<div class="container">*@
        <div class="navbar-header" style="background-color:black">

            <img src=" ~/Content/logo-edited.jpg" alt="online banking " ;width="80" ; height="80" ; style="margin-top:5px;margin-left:5px">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right" style="margin-left:850px;color:white">

                    <li style="color:black;font-size:20px">
                        @Html.ActionLink("About", "aboutbank", "aboutbank")
                    </li>
                    <li style="text-emphasis-color:black;font-size:20px">@Html.ActionLink("Faq", "faqbank", "faqbank")</li>
                    <li style="text-emphasis-color:black;font-size:20px">@Html.ActionLink("Home", "frontpage", "frontpage") </li>
                    <li style="text-emphasis-color:black;font-size:20px">
                        @Html.ActionLink("Login", "login", "login")
                    </li>
                    @*<li style="background-color:White;font-size:20px"><a href="~/Views/Shared/loginlayout.cshtml">Login</a></li>*@
                </ul>
            </div>
            <div style="margin-top:-130px;margin-left:150px">

                <h1 style="color:white">STANDARD BANK</h1>

            </div>

        </div>

    </nav>

</body>
@RenderBody()

    <div class="container-fluid bg-grey" style="margin-left:24px;">
        <h2 class="text-center" style="color:white">CONTACT</h2>
        <div class="row">
            <div class="col-sm-5">
                <h4 style="color:white">Contact us and we'll get back to you within 24 hours.</h4>
                <h2 style="color:white">INDIA</h2>
                <h2 style="color:white"> 088-66-55-44</h2>
                <h2 style="color:white"> myemail@bank.com</h2>
            </div>
            <div class="col-sm-7">
                <div class="row">
                    <div class="col-sm-6 form-group">
                        <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
                    </div>
                    <div class="col-sm-6 form-group">
                        <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
                    </div>
                </div>
                <textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea><br>
                <div class="row">
                    <div class="col-sm-12 form-group" style="margin-right:20px">
                        <button class="#" type="submit">Send</button>
                    </div>
                </div>
            </div>
        </div>
    </div>







</html>

Retail_Banking_Group2/Views/Shared/faqbank.cshtml
<!DOCTYPE html>
<html>
<head>
    @*<font style="margin-left:10px;margin-top:1px;font-size:50px;color:white;position:fixed"> STANDARD BANK</font>*@
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Retail Banking</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>


    <body style="background-color:white;background-image:url(http://www.healingandtransformation.com/wp-content/uploads/2014/05/bigstock-Sky-and-clouds-background-26443844.jpg);background-size:cover;background-repeat:no-repeat">
</head>
</body>
@RenderBody()
<nav class="navbar navbar-default " style="margin-top:-50px;margin-left:0px;background-color:black;">
    @*<div class="container">*@
    <div class="navbar-header" style="background-color:black">

        <img src=" ~/Content/logo-edited.jpg" alt="online banking " ;width="80" ; height="80" ; style="margin-top:5px;margin-left:5px">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right" style="margin-left:850px;color:white">

                <li style="color:black;font-size:20px">
                    @Html.ActionLink("About", "aboutbank", "aboutbank")
                </li>
                <li style="text-emphasis-color:black;font-size:20px">@Html.ActionLink("Home", "frontpage", "frontpage")</li>
                <li style="text-emphasis-color:black;font-size:20px">@Html.ActionLink("Contact", "contactbank", "contactbank") </li>
                <li style="text-emphasis-color:black;font-size:20px">
                    @Html.ActionLink("Login", "login", "login")
                </li>
                @*<li style="background-color:White;font-size:20px"><a href="~/Views/Shared/loginlayout.cshtml">Login</a></li>*@
            </ul>
        </div>
        <div style="margin-top:-130px;margin-left:150px">

            <h1 style="color:white">STANDARD BANK</h1>

        </div>

    </div>

</nav>


</body>

<div class="container-fluid" style="margin-top:100px">
    <div class="text-center">
        @*<h2 style="margin-top:100px">STANDARD BANK</h2>*@
        <h4 style="color:white">Commonly Asked Question</h4>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-default text-center">
                <div class="panel-heading">
                    <h1>LOANS</h1>
                </div>
                <div class="panel-body">               
                </div>
                <div class="panel-footer">
                    <h3>8.99%</h3>
                    <h4>per month</h4>
                    <button class="btn btn-lg">apply</button>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-default text-center">
                <div class="panel-heading">
                    <h1>Cheque</h1>
                </div>
                <div class="panel-body">
                    <p><strong>how to get a new  cheque book</strong></p>
                    @*<p><strong>25</strong> Ipsum</p>
                    <p><strong>10</strong> Dolor</p>
                    <p><strong>5</strong> Sit</p>
                    <p><strong>Endless</strong> Amet</p>*@
                </div>
                <div class="panel-footer">
                    <h3>Fill the last page and submit it to bank or apply below</h3>
                    <h4>No Extra charges</h4>
                    <button class="btn btn-lg">apply</button>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-default text-center">
                <div class="panel-heading">
                    <h1>I asked the bank to lower the fees on my account. It refused. Can it do that?</h1>
                </div>
                <div class="panel-body">
                    <p><strong>It is directed by RBI</strong></p>
                    @*<p><strong>50</strong> Ipsum</p>
                    <p><strong>25</strong> Dolor</p>
                    <p><strong>10</strong> Sit</p>
                    <p><strong>Endless</strong> Amet</p>*@
                </div>
                <div class="panel-footer">
                    <h3>Updated</h3>
                    <h4>asper RBI Directions</h4>
                    <button class="btn btn-lg">Different Questions</button>
                </div>
            </div>
        </div>
    </div>
</div>
</html>